server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
#    false和fetchRegistry：false来表明自己是一个eureka server.
#    http://localhost:8761 监控页面看到不到自己(No instances available)是因为配置成了false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server